### PR TITLE
Add converters to hashes and mashes

### PR DESCRIPTION
**Pull request by nepalez**
``` ruby
container.register(:item, 'data')

container.to_h    # => { item: 'data' }
container.to_hash # => { 'item' => 'data' }
container.to_mash # => <Hashie::Mash {'item' => 'data'}>
```

### CODE REVIEW

**Comment by flash-gordon** [comment]
@nepalez why would you need it in the lib? Adding one more runtime dependency for one method seems redundant to me because you always can do something like that:

``` ruby
class MyAppContrainer
  extend Dry::Container::Mixin

  def self.to_hash
    keys.inject({}) { |a, e| a.merge e.to_s => self[e] }
  end

  def self.to_mash
    Hashie::Mash.new(to_hash)
  end
end
```

And `inject` + `merge` should be replaced with `each_with_object` due to performance reasons.

**Comment by nepalez** [comment]
@flash-gordon you're right, thanks!

I kept `#to_h` (for symbolized keys) and `#to_hash` (for stringified ones) and dropped `#to_mash`

I feel this PR needs some more work to stringify not only the root keys, but namespaces' ones as well.

**Comment by AMHOL** [comment]
@nepalez what is the requirement here? Not adding the to_hash interface to container was a conscious decision.

**Comment by nepalez** [comment]
@AMHOL In my current project I planned to use the gem to containerize a state of application. Pretty common task.

But I have a tiny problem with the interface. In addition of `[]` or `resolve`, I need plain methods for sending a container to various [roar](https://github.com/apotonick/roar)-based representers. The recipy is simple `Hashie::Mash.new container.to_hash`.

I agree to @flash-gordon that `to_mash` was an overkill. From the other hand, the current interface by itself is not so standard to use it with other objects easiliy. I use hashification as a sort of "normalizing" it.

**Comment by nepalez** [comment]
IMO its time to close it

**Comment by AMHOL** [comment]
Sorry @nepalez forgot about this, I still don't think this functionality is necessary, you shouldn't be passing the container around like that, the whole point is that it's a central repository for your objects. I wouldn't be opposed to an interface for resolving multiple key/value pairs to a hash though, as long as the keys are specified

**Comment by nepalez** [comment]
@AMHOL no problem :) I just wanted to make final decision

A real problem with this PR is my trial to use the gem in a different context, where "container" means not 

> a central repository for objects

but something like a wrapper around pre-existing ones (some sort of facade pattern)

**Pull request closed without merging**
