### PR TITLE
Change registration to block only and use singleton option

### PR DESCRIPTION
**Pull request by AMHOL**

### CODE REVIEW

**Comment by tylerhunt** [comment]
What's the status on this? Is the `:singleton` option still on the table?

**Comment by AMHOL** [comment]
Hi @tylerhunt, I'm not sure at the moment, it needs more discussion, feel free to open one up on Gitter

**Comment by solnic** [comment]
I'm having second thoughts about this. Maybe it would be better to control this on the class level with some singleton mixin

**Comment by AMHOL** [comment]
Not sure about that @solnic, would that mean having a separate container to register singletons with? Personally, I like the interface introduced by this PR, means that we can register singletons and still resolve its dependencies inside of the block argument, and makes a consistent interface, implementation could be better TBF, thinking I went overkill with the configuration options here?

**Comment by solnic** [comment]
@AMHOL would be awesome if this could work like it does now with the exception of `singleton` option which would add the singleton behavior. Not sure if that's doable though. One issue I had is singletons in tests becoming sort-of-globals that I couldn't replace in tests when I actually want to use a stubbed dependency. This is another big subject, kind of related to this.

**Pull request closed without merging**
