### PR TITLE
Use #parameters instead of #arity

### PR DESCRIPTION
**Pull request by flash-gordon**

### CODE REVIEW

**Comment by AMHOL** [comment]
Thanks @flash-gordon, not sure why this is needed as the arity check was there to check whether the block/proc argument takes no arguments?

Also the build is broken on jruby, not sure what the problems is though

**Comment by flash-gordon** [comment]
damn! I tested every mri since 2.0 manually. I guess jruby 1.7 doesn't support keywords in block, I'll figure that out.

When you pass a block to a method it is converted to a proc (not lambda) object that has some weird behavior with `#arity`:

``` ruby
2.3.0 :001 > (-> * {}).arity
 => -1
2.3.0 :002 > (-> ** {}).arity
 => -1
2.3.0 :003 > (proc { |*| }).arity
 => -1
2.3.0 :004 > (proc { |**| }).arity
 => 0
```

and

``` ruby
2.3.0 :001 > def foo(&block)
2.3.0 :002?>   block
2.3.0 :003?>   end
 => :foo
2.3.0 :004 > (foo { |**| }).arity
 => 0
```

I use keyword arguments quite extensively with dry-transaction and it works fine except this case because dry-container tries to call the block prematurely.

**Comment by solnic** [comment]
We don't support jruby 1.7

**Comment by flash-gordon** [comment]
@solnic OK, I updated travis config, we'll see what happens

**Comment by flash-gordon** [comment]
Doesn't work either :-/ Going to take a look later today

**Comment by flash-gordon** [comment]
It works on my machine with jruby-9000 and fails on CI because travis installs jruby-9000.pre1 instead of released version due to unfixed [rvm issue](https://github.com/rvm/rvm/issues/3475). Travis has [workaround](https://github.com/travis-ci/travis-ci/issues/4720#issuecomment-136000801) for that but it slows the build down (compare [this](https://travis-ci.org/dry-rb/dry-container/builds/126547927) and [that](https://travis-ci.org/dry-rb/dry-container/builds/126919639)).

**Comment by flash-gordon** [comment]
@AMHOL your turn :)

**Comment by flash-gordon** [comment]
btw I used workaround [from here](https://github.com/department-of-veterans-affairs/connect_vbms/blob/44af05841998ad5707db28135d215f2ac069148b/.travis.yml#L29-L37)

**Comment by AMHOL** [comment]
Sorry @flash-gordon updated to jruby-9000 in travis.yml, I missed that the first time, specs are failing again but they actually run

**Comment by flash-gordon** [comment]
@AMHOL I tried that. Now the build uses jruby-9000-pre1 again :)

```
$ java -Xmx32m -version
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)
$ javac -J-Xmx32m -version
javac 1.7.0_76
$ ruby --version
ruby --version
jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab Java HotSpot(TM) 64-Bit Server VM 24.76-b04 on 1.7.0_76-b13 [linux-amd64]
```

The only way is to update rvm & install jruby manually.

**Comment by AMHOL** [comment]
That sucks, removed my commit

**Comment by flash-gordon** [comment]
Yep, it does. IIUIC travis doesn't update rvm for god-knows-why reason.

**Pull request merged**
